### ISSUE TITLE
Trời ơi cái quần què gì dậy:)))

### ISSUE THREAD

**Issue by KDRXD** [miraiPr0ject/miraiv2#2]
Lỗi này là lỗi gì thế ad ới ời
![image_2021-06-10_145134](https://user-images.githubusercontent.com/66688696/121486456-5a117580-c9fb-11eb-959e-8d1d9f148478.png)

**Comment by huybopbi** [comment]
> Lỗi này là lỗi gì thế ad ới ời
> ![image_2021-06-10_145134](https://user-images.githubusercontent.com/66688696/121486456-5a117580-c9fb-11eb-959e-8d1d9f148478.png)

vào acc xác minh và lấy lại appstate

**Comment by KDRXD** [comment]
> > Lỗi này là lỗi gì thế ad ới ời
> > ![image_2021-06-10_145134](https://user-images.githubusercontent.com/66688696/121486456-5a117580-c9fb-11eb-959e-8d1d9f148478.png)
> 
> vào acc xác minh và lấy lại appstate

Xác minh cái gì ạ ?:Đ

**Comment by KDRXD** [comment]
Với lấy lại appstate kiểu gì được
Gõ lại lệnh nom login hả ?:v

**Comment by KDRXD** [comment]
*npm

**Comment by huybopbi** [comment]
> Với lấy lại appstate kiểu gì được
> Gõ lại lệnh nom login hả ?:v

node login, xem thông báo fb nếu có thì xác minh

**Comment by catalizcs** [comment]
cung cấp giúp tui thông tin sau:
- version nodejs
- version npm
- hệ điều hành đang sử dụng

**Comment by KDRXD** [comment]
Nodejs v16.3.0
npm 7.15.1
Hệ điều hành Windows 10 x64

**Comment by KDRXD** [comment]
À giờ thì được rồi=)))

**Comment by KDRXD** [comment]
Nhưng thỉnh thoảng có một đống chữ đỏ liên quan tới cái gì autoUnsend

**Comment by catalizcs** [comment]
> Nhưng thỉnh thoảng có một đống chữ đỏ liên quan tới cái gì autoUnsend

hmmmmm check lại update mới nhé :0
