### ISSUE TITLE
setrankup gif không được

### ISSUE THREAD

**Issue by xcloudx12345** [miraiPr0ject/miraiv2#5]
setrankup gif bị báo hết dung lượng hoặc lỗi mạng, đã vô mò và thấy là do code trong module bị sai dir gif

**Comment by catalizcs** [comment]
Cho xin version trong package.json ông ơi

**Comment by xcloudx12345** [comment]
![image](https://user-images.githubusercontent.com/40192522/123057510-24747f80-d432-11eb-9c08-ce4bd0aa552d.png)
![image](https://user-images.githubusercontent.com/40192522/123057544-2b9b8d80-d432-11eb-9e1f-5e8dfc147470.png)
trước khi up ver 1.2.4 có thử set thì không được, mà lười mò, sau up 1.2.4 vẫn bị nên đi mò mới phát hiện

**Comment by catalizcs** [comment]
@xcloudx12345 check thử version 1.2.7 còn lỗi không ông nhé!

**Comment by xcloudx12345** [comment]
> @xcloudx12345 check thử version 1.2.7 còn lỗi không ông nhé!

đã test, ok rồi bạn êi
