### ISSUE TITLE
Report bugs

### ISSUE THREAD

**Issue by kaynk8** [miraiPr0ject/miraiv2#6]
Lỗi:
he request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
khi dùng lệnh sing + tên bài hát
![Captur2e](https://user-images.githubusercontent.com/51262050/123547405-dbeaf800-d78a-11eb-8b73-65819a56ba5f.PNG)

**Comment by ntkhang03** [comment]
> Lỗi:
> he request cannot be completed because you have exceeded your [quota](/youtube/v3/getting-started#quota).
> khi dùng lệnh sing + tên bài hát
> ![Captur2e](https://user-images.githubusercontent.com/51262050/123547405-dbeaf800-d78a-11eb-8b73-65819a56ba5f.PNG)

Thay key api YouTube ở file config.json

**Comment by catalizcs** [comment]
Do api key v3 tôi cung câp bị quá tải nhé, có thể tìm cách get key trên google
