### ISSUE TITLE
Wrong username/password.

### ISSUE THREAD

**Issue by tungnnt** [miraiPr0ject/miraiv2#8]
Sau khi config ```email```, ```password```, ```botname``` trong ```config.json```, và chạy ```node login.js```, thì mình gặp lỗi này ```{ error: 'Wrong username/password.' }```

**Comment by catalizcs** [comment]
Bạn cung cấp giúp mình một số thông tin cần thiết sau đây:
- NodeJS version
- Source code version(Có thể tìm thấy trong package.json)
- Bạn có đang sử dụng VPN của dịch vụ vào không?
