### ISSUE TITLE
lỗi người dùng

### ISSUE THREAD

**Issue by anhhadz123** [miraiPr0ject/miraiv2#9]
bot đang hoạt động phát sinh lỗi ko sử dụng được lệnh

**Comment by anhhadz123** [comment]
,

**Comment by catalizcs** [comment]
Bạn cung cấp giúp mình một số thông tin cần thiết sau đây:

- NodeJS version
- Source code version(Có thể tìm thấy trong package.json)
- Tài khoản của bạn có đang bị block tính năng hay không?
